version: "3"

dotenv: ['.env']

tasks:

  # RUN

  run-local:
    desc: Run main application
    cmd: go run ./cmd/file_svc

  mongo:
    desc: Run mongodb container
    cmd: $CONTAINER_ENGINE compose -f ./deploy/mongodb.compose.yaml up -d --build
